### ISSUE TITLE
Unkown USB device after downloading firmware (through ArduinoIDE)

### ISSUE THREAD

**Issue by Bruur-vr** [wagiminator/CH552-MacroPad-plus#6]
Hello,

Before downloading this firmware the CH552 showed up as 4 different HID devices, I did not like the firmware it came with (I had no way of changing buttons) so I tried overwriting it through ArduinoIDE. I had no problem uploading when CH552 was in bootloader mode.

I adjusted the config.h since the premade board had the switches and encoder wired differently. Also it only has 6NeoPixels.
When first connecting (with old firmware) usbview said that max load was 100mA so I changed that too.

I installed everything in ArduinoIDE, selected board and adjusted parameters under "tools". Then hit upload while it was in bootloader mode. There was something about running "make flash" but that did not work for me: I also thought you either do it through ArduinoIDE or through makefile, right?

Since the upload it shows as Unknown USB device.
![afbeelding](https://github.com/user-attachments/assets/1f00a2d4-e16f-4aec-88ec-22247b0db314)

"Windows has stopped this device because it has reported problems. (Code 43)"

Problem code is 0000002B

Events says this:
```
Device USB\VID_0000&PID_0005\5&38e97a59&0&7 was not migrated due to partial or ambiguous match.

Last Device Instance Id: USB\VID_0000&PID_0003\6&31b1809d&0&1
Class Guid: {36fc9e60-c465-11cf-8056-444553540000}
Location Path: 
Migration Rank: 0xF000FFFFFFFFF100
Present: false
Status: 0xC0000719
```

in usbview it shows up like this:
![afbeelding](https://github.com/user-attachments/assets/a8f6b98a-5e8e-4557-b6a1-8c8e3af53f94)

Zadig shows up as it having no driver when out of bootloader mode.
![afbeelding](https://github.com/user-attachments/assets/87fe75d5-04f1-4e07-930c-72a919a0e8c5)

When in bootloader it shows this, after I tried reïnstalling drivers (WINusb & libusb) but it makes no difference.
![afbeelding](https://github.com/user-attachments/assets/3e8dbfc6-5fc6-45f9-bff3-86e8ba425ba5)

I am not well versed in these kind of topics so forgive me for not understanding in the first try.

**Comment by Bruur-vr** [comment]
Good news,
I got it working.

![afbeelding](https://github.com/user-attachments/assets/d5a5413d-a4d3-4a1d-8abf-ff251173a296)

The prompt to run (after doing "cd" command to the right directory):
`python3 ./tools/chprog.py macropad_plus.bin`
Did not work. It said Python was not installed (while it was). I deleted the "3" and ran it again: and there was the message you see in the image.

**Comment by Bruur-vr** [comment]
Since i'm using a prebuild Macro Pad: I tried changing the parameters, like adjusting the amount of neopixels and added macro's to the keys: letting them type their own key nr. by using "KBD_type('1');" (troubleshooting what button is connected in comparison with your template).

After Uploading through Arduino the same problem persists: Unkown USB device.
The only way to get a "working" USB device is by using the  python `./tools/chprog.py macropad_plus.bin` command. But then my macro's are overwritten by the default program.

I tried export compiled binary, it gives a hex file. I put this in WCHISPstudio but after flashing I get the same "USB device not recognized" message again.
![afbeelding](https://github.com/user-attachments/assets/16d0ea96-244a-41ec-8c9e-0586a2c70a8f)

In a last effort I tried running:
`python ./tools/chprog.py macropad_plus.hex `
where the .hex file is outputted by ArduinoIDE, but that seemed to make the USB device not show up at all unless I reinstall CH372 driver, and then only in bootloader mode.

**Comment by wagiminator** [comment]
Hi, I don't know why, but depending on the version it may not work if you compile with ArduinoIDE. If you are able to compile with the makefile, then please try this.

**Comment by Bruur-vr** [comment]
I am sorry, what are you referring to with "try this"?
If you mean trying to compile with makefile then the result is given in my original post: I get unknown USB device message.
If you mean trying to compile with an older version of arduino: I'll try with the legacy version (1.8.7) instead of 2.3.3 version and edit this post with the result in a few minutes.

EDIT: done with legacy v1.8.19
![afbeelding](https://github.com/user-attachments/assets/4a10f29f-c2e1-44e8-8f52-fd746271518d)
Same results unfortunately.

EDIT2: I tried `python ./tools/chprog.py macropad_plus.ino.ch552.hex` where the .hex is the compiled binary from the 1.8.19 ArduinoIDE, but it does not seem to find my CH522. 
```
Connecting to device ...
ERROR: No CH55x device found!
Check if device is in boot mode or check driver.
```
Zadig does find it and it says the driver is the CH372 driver. I'll try with the WCHISPstudio application.

EDIT3: Alas, same result.

**Comment by Bruur-vr** [comment]
Maybe the `make flash` cmd will make the right firmware?
If I try it, it returns:
```
C:\Users\xxxx\Desktop\macropad_plus>make flash
'make' is not recognized as an internal or external command,
operable program or batch file.
```
I have python 3, psyusb and SDCC installed as per instruction.

**Comment by Bruur-vr** [comment]
[DeqingSun](https://github.com/DeqingSun) suggested using ch55xduino version 0.0.16, and it seemed to work.
The standard version that is installed is 0.0.25: You can downgrade it farther than 0.0.23 with ArduinoIDE legacy.
